version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
build:
  parallel: true
  verbosity: minimal
platform:
  - x64
  - Win32
  
after_build:
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\Editor.exe %APPVEYOR_BUILD_FOLDER%\Editor
  - cmd: 7z a WickedEngineEditor.zip WickedEngine\shaders\ WickedEngine\fonts\ images\ models\ scripts\ shadercompilers\ Documentation\ *.py *.txt *.md Editor\Editor.exe Editor\images\ Editor\sound\ Editor\*.ini Editor\*.ico Editor\*.lua
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\Tests.exe %APPVEYOR_BUILD_FOLDER%\Tests
  - cmd: 7z a WickedEngineTests.zip WickedEngine\shaders\ WickedEngine\fonts\ images\ models\ scripts\ shadercompilers\ Documentation\ *.py *.txt *.md Tests\Tests.exe Tests\images\ Tests\sound\ Tests\*.ini Tests\*.ico Tests\*.lua Tests\*.ttf
  
artifacts:
- path: WickedEngineEditor_%PLATFORM%.zip
  name: Editor_%PLATFORM%
- path: WickedEngineTests_%PLATFORM%.zip
  name: Tests_%PLATFORM%

